common:
  vpn_cidr: "10.1.0.0/16"

workspaces:
  nonprod-us-east-1-default:
    aws:
      account_id: 123456789
      region: us-east-1
    account_name: nonprod
    project_name: test
    project_name_prefix: test
    zone:  
      createZone: true
      vpc_id: "vpc-07e3c626b44400ee2"
      domain_name: "test"
    records:
      test:
        type: "A"
        ttl: 3600
        records: ["10.10.10.10"]
      test2:
        type: "A"
        ttl: 3600
        records: ["10.10.10.20"]